version: '3.8'

services:
  redis-node-1:
    image: redis:7.2
    container_name: redis-node-1
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - ./redis/:/usr/local/etc/redis/
    networks:
      redis-cluster:
        ipv4_address: 172.28.0.2

  redis-node-2:
    image: redis:7.2
    container_name: redis-node-2
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - ./redis/:/usr/local/etc/redis/
    networks:
      redis-cluster:
        ipv4_address: 172.28.0.3

  redis-node-3:
    image: redis:7.2
    container_name: redis-node-3
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - ./redis/:/usr/local/etc/redis/
    networks:
      redis-cluster:
        ipv4_address: 172.28.0.4

  redis-node-4:
    image: redis:7.2
    container_name: redis-node-4
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - ./redis/:/usr/local/etc/redis/
    networks:
      redis-cluster:
        ipv4_address: 172.28.0.5

  redis-node-5:
    image: redis:7.2
    container_name: redis-node-5
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - ./redis/:/usr/local/etc/redis/
    networks:
      redis-cluster:
        ipv4_address: 172.28.0.6

  redis-node-6:
    image: redis:7.2
    container_name: redis-node-6
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - ./redis/:/usr/local/etc/redis/
    networks:
      redis-cluster:
        ipv4_address: 172.28.0.7

  redis-node-7:
    image: redis:7.2
    container_name: redis-node-7
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - ./redis/:/usr/local/etc/redis/
    networks:
      redis-cluster:
        ipv4_address: 172.28.0.8

  redis-node-8:
    image: redis:7.2
    container_name: redis-node-8
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - ./redis/:/usr/local/etc/redis/
    networks:
      redis-cluster:
        ipv4_address: 172.28.0.9

  redis-node-9:
    image: redis:7.2
    container_name: redis-node-9
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - ./redis/:/usr/local/etc/redis/
    networks:
      redis-cluster:
        ipv4_address: 172.28.0.10
  
  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    ports:
      - "5540:5540"
    networks:
      redis-cluster:
        ipv4_address: 172.28.0.11

  cluster-init:
    image: redis:7.2
    depends_on:
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
      - redis-node-5
      - redis-node-6
      - redis-node-7
      - redis-node-8
      - redis-node-9
    volumes:
      - ./scripts/init-cluster.sh:/init-cluster.sh
    entrypoint: ["/bin/sh", "-c", "sleep 5 && /init-cluster.sh"]
    networks:
      redis-cluster:

networks:
  redis-cluster:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
